#! /usr/bin/env python
import sys
from hooks import get_active_hooks


if __name__ == '__main__':
    temp_msg_file = sys.argv[1]
    for hook in get_active_hooks('commit-msg'):
        print('Running hook: {}'.format(hook.__name__))
        hook(temp_msg_file)
