#! /usr/bin/env python
import sys
try:
    from hooks import get_active_hooks
except ImportError:
    print('Cannot import hooks. '
          'Did you do `pip install hooks` or are you in the right virtualenv?')
    sys.exit(0)


if __name__ == '__main__':
    for hook in get_active_hooks("$hook_type"):
        print('Running hook: {}'.format(hook.__name__))
        if not hook(*sys.argv[1:]):
            sys.exit(1)
