#! /usr/bin/env python
import sys
from hooks import get_active_hooks


if __name__ == '__main__':
    temp_msg_file = sys.argv[1]
    for hook in get_active_hooks('prepare-commit-msg'):
        hook(temp_msg_file)
